name: Testing

on:
  push:
    branches: [main]

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables
        run: |
          echo "CYPRESS_UI_ENDPOINT=${{ secrets.CYPRESS_UI_ENDPOINT }}" >> $GITHUB_ENV
          echo "CYPRESS_SUPER_ADMIN_EMAIL=${{ secrets.CYPRESS_SUPER_ADMIN_EMAIL }}" >> $GITHUB_ENV
          echo "CYPRESS_SUPER_ADMIN_PASSWORD=${{ secrets.CYPRESS_SUPER_ADMIN_PASSWORD }}" >> $GITHUB_ENV

      - name: Run Cypress tests
        run: npx cypress run --reporter cypress-mochawesome-reporter

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
            cypress/reports/html

  Report:
    needs: Testing
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download test artifacts
        uses: actions/download-artifact@v4.1.4
        with:
          name: cypress-artifacts
          path: cypress-artifacts

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress-artifacts/cypress/reports/html
